<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO3rWtYP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO3rWtYP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO3rWtYP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO3rWtYP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO3rWtYP\App_KernelDevDebugContainer([
    'container.build_hash' => 'O3rWtYP',
    'container.build_id' => '17fa941b',
    'container.build_time' => 1616766125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO3rWtYP');
